name: Receive repository dispatch event

on:
  # Listen to a repository dispatch event by the name of `dispatch-event`
  repository_dispatch:
    types: [update-references]
  workflow_dispatch:

jobs:
    create-pull-request:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v2
          - name: Create Pull Request
            run: gh pr create -B main -H test --title 'Merge test into main' --body 'Created by Github action'
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    